/*
gl_cubemaps.cpp - tools for cubemaps search & handling
Copyright (C) 2016 Uncle Mike

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
*/

#include "hud.h"
#include "utils.h"
#include "r_local.h"
#include "event_api.h"
#include "const.h"
#include "com_model.h"
#include "ref_params.h"
#include "mathlib.h"
#include "r_world.h"
#include "pm_defs.h"

static Vector env_dir[] =
{
	Vector( 1.0f,  0.0f,  0.0f ),
	Vector( -1.0f,  0.0f,  0.0f ),
	Vector( 0.0f,  1.0f,  0.0f ),
	Vector( 0.0f, -1.0f,  0.0f ),
	Vector( 0.0f,  0.0f,  1.0f ),
	Vector( 0.0f,  0.0f, -1.0f )
};

/*
==================
Mod_FreeCubemap

unload a given cubemap
==================
*/
static void Mod_FreeCubemap( mcubemap_t *m )
{
	if( m->valid && m->texture && m->texture != tr.whiteCubeTexture )
		FREE_TEXTURE( m->texture );

	memset( m, 0, sizeof( *m ) );
}

/*
==================
Mod_FreeCubemaps

purge all the cubemaps
from current level
==================
*/
void Mod_FreeCubemaps( void )
{
	for( int i = 0; i < world->num_cubemaps; i++ )
		Mod_FreeCubemap( &world->cubemaps[i] );
	Mod_FreeCubemap( &world->defaultCubemap );

	world->rebuilding_cubemaps = CMREBUILD_INACTIVE;
	world->build_default_cubemap = false;
	world->loading_cubemaps = false;
	world->cubemap_build_number = 0;
	world->num_cubemaps = 0;
	world->cubemaps_ready = false;
}

/*
==================
Mod_CheckCubemap

check cubemap sides for valid
==================
*/
static bool Mod_CheckCubemap( const char *name )
{
	char *suf[6] = { "px", "nx", "py", "ny", "pz", "nz" };
	int	valid_sides = 0;
	char	sidename[64];
	int	iCompare;

	// FIXME: potentially unsafe checking: looking for DDS_CUBEMAP bit?
	if( FILE_EXISTS( va( "maps/env/%s/%s.dds", world->name, name ) ) )
		return true;

	for( int i = 0; i < 6; i++ )
	{
		Q_snprintf( sidename, sizeof( sidename ), "maps/env/%s/%s%s.tga", world->name, name, suf[i] );

		if( COMPARE_FILE_TIME( worldmodel->name, sidename, &iCompare ) && iCompare <= 0 )
			valid_sides++;
	}

	return (valid_sides == 6) ? true : false;
}

/*
==================
Mod_DeleteCubemap

remove cubemap images from HDD
==================
*/
static void Mod_DeleteCubemap( const char *name )
{
	char *suf[6] = { "px", "nx", "py", "ny", "pz", "nz" };
	char	sidename[64];

	for( int i = 0; i < 6; i++ )
	{
		Q_snprintf( sidename, sizeof( sidename ), "maps/env/%s/%s%s.tga", world->name, name, suf[i] );

		if( FILE_EXISTS( sidename ) )
			Sys_RemoveFile( sidename );
	}
}

void Mod_LoadCubemapBoxes( void )
{
	// loading cubemaps only when it's supported
	if( !GL_Support( R_TEXTURECUBEMAP_EXT ) )
		return;

	if( tr.lowmemory )
		return;

	// parse the cubemap file (it's generated by special CSG compiler, from "cubemap_box" entity brushes)
	char *pfile;
	char token[256];
	char path[1024];
	Q_snprintf( path, sizeof( path ), "maps/%s_cubemaps.txt", world->name );
	char *afile = (char *)gEngfuncs.COM_LoadFile( path, 5, NULL );
	if( !afile )
		return;

	mcubemap_t *out = world->cubemaps;
	world->rebuilding_cubemaps = CMREBUILD_INACTIVE;
	int count = 0;

	while( (afile = COM_ParseFile( afile, token )) != NULL )
	{
		if( !afile )
			break;

		if( count >= MAX_MAP_CUBEMAPS )
			break;

		if( !Q_stricmp( token, "cmbox" ) ) // box line start
		{
			// mins
			afile = COM_ParseLine( afile, token );
			if( afile && token[0] > 0 )
			{
				Q_atov( out->mins, token, 3 );
			}
			else break;

			// maxs
			afile = COM_ParseLine( afile, token );
			if( afile && token[0] > 0 )
			{
				Q_atov( out->maxs, token, 3 );
			}
			else break;

			// origin
			afile = COM_ParseLine( afile, token );
			if( afile && token[0] > 0 )
			{
				Q_atov( out->origin, token, 3 );
			}
			else break;

			// size
			out->size = DEFAULT_CUBEMAP_SIZE;
			afile = COM_ParseLine( afile, token );
			if( afile && token[0] > 0 )
			{
				out->size = Q_atoi( token );
				out->size = NearestPOW( out->size, false );
				out->size = bound( 1, out->size, 512 );
			}
			else break;

			// build a cubemap name like enum
			Q_snprintf( out->name, sizeof( out->name ), "maps/env/%s/cube#%i", world->name, count );
			out->valid = Mod_CheckCubemap( va( "cube#%i", count ) ); // need for rebuild?
			if( !out->valid )
				world->rebuilding_cubemaps = CMREBUILD_INACTIVE_NEEDSREBUILD;

			out++;
			count++;
		}
	}

	ConPrintf( "Loaded %i cubemap boxes.\n", count );
	world->num_cubemaps = count;
	world->loading_cubemaps = (count > 0) ? true : false;

	// makes an default cubemap from skybox
	if( FBitSet( world->features, WORLD_HAS_SKYBOX ) && (count > 0) )
	{
		mcubemap_t *cm = &world->defaultCubemap;
		Q_snprintf( cm->name, sizeof( cm->name ), "maps/env/%s/default", world->name );
		cm->origin = (worldmodel->mins + worldmodel->maxs) * 0.5f;
		cm->size = 256; // default cubemap larger than others
		cm->valid = Mod_CheckCubemap( "default" ); // need for rebuild?
		world->loading_cubemaps = true;

		if( !cm->valid )
		{
			world->rebuilding_cubemaps = CMREBUILD_INACTIVE_NEEDSREBUILD;
			world->build_default_cubemap = true;
		}
	}
	else
	{
		// using stub as default cubemap
		mcubemap_t *cm = &world->defaultCubemap;
		Q_snprintf( cm->name, sizeof( cm->name ), "*whiteCube" );
		cm->origin = (worldmodel->mins + worldmodel->maxs) * 0.5f;
		cm->texture = tr.whiteCubeTexture;
		cm->valid = true;
		cm->size = 4;
	}

	// do not autorebuild
	if( world->rebuilding_cubemaps == CMREBUILD_INACTIVE_NEEDSREBUILD )
	{
		ConPrintf( "^3Warning:^7 Map has %i cubemaps which require rebuilding. Run 'buildcubemaps' to build them.\n", world->num_cubemaps );
		world->build_default_cubemap = false;
		world->cubemaps_ready = false;
	}
	else if( world->loading_cubemaps )
	{
		world->cubemaps_ready = true;
	}
}

/*
==================
Mod_LoadCubemap

load cubemap into
video memory
==================
*/
static bool Mod_LoadCubemap( mcubemap_t *m )
{
	int flags = 0;

	if( m->valid && !m->texture )
	{
		if( GL_Support( R_SEAMLESS_CUBEMAP ) )
			SetBits( flags, TF_BORDER );	// seamless cubemaps have support for border
		else SetBits( flags, TF_CLAMP ); // default method
		m->texture = LOAD_TEXTURE( m->name, NULL, 0, flags );

		// make sure it's really a cubemap
		if( RENDER_GET_PARM( PARM_TEX_TARGET, m->texture ) == GL_TEXTURE_CUBE_MAP_ARB )
			m->valid = true;
		else m->valid = false;

		// NOTE: old DDS cubemaps has no mip-levels
		m->numMips = RENDER_GET_PARM( PARM_TEX_MIPCOUNT, m->texture );
	}

	return m->valid;
}

/*
=================
Mod_LoadCubemaps
=================
*/
void Mod_LoadCubemaps( const byte *base, const dlump_t *l )
{
	dcubemap_t *in;
	mcubemap_t *out;
	int	i, count;

	world->rebuilding_cubemaps = CMREBUILD_INACTIVE;

	in = (dcubemap_t *)(base + l->fileofs);
	if( l->filelen % sizeof( *in ) )
		HOST_ERROR( "Mod_LoadCubemaps: funny lump size\n" );
	count = l->filelen / sizeof( *in );

	if( count >= MAX_MAP_CUBEMAPS )
	{
		ALERT( at_error, "Mod_LoadCubemaps: map contain too many cubemaps. Will handle only first %i items\n", MAX_MAP_CUBEMAPS );
		count = MAX_MAP_CUBEMAPS;
	}

	out = world->cubemaps;
	world->num_cubemaps = count;
	world->loading_cubemaps = (count > 0) ? true : false;

	// makes an default cubemap from skybox
	if( FBitSet( world->features, WORLD_HAS_SKYBOX ) && (count > 0) )
	{
		mcubemap_t *cm = &world->defaultCubemap;
		Q_snprintf( cm->name, sizeof( cm->name ), "maps/env/%s/default", world->name );
		cm->origin = (worldmodel->mins + worldmodel->maxs) * 0.5f;
		cm->size = 256; // default cubemap larger than others
		cm->valid = Mod_CheckCubemap( "default" ); // need for rebuild?
		world->loading_cubemaps = true;

		if( !cm->valid )
		{
			world->rebuilding_cubemaps = CMREBUILD_INACTIVE_NEEDSREBUILD;
			world->build_default_cubemap = true;
		}
	}
	else
	{
		// using stub as default cubemap
		mcubemap_t *cm = &world->defaultCubemap;
		Q_snprintf( cm->name, sizeof( cm->name ), "*whiteCube" );
		cm->origin = (worldmodel->mins + worldmodel->maxs) * 0.5f;
		cm->texture = tr.whiteCubeTexture;
		cm->valid = true;
		cm->size = 4;
	}

	for( i = 0; i < count; i++, in++, out++ )
	{
		// build a cubemap name like enum
		Q_snprintf( out->name, sizeof( out->name ), "maps/env/%s/cube#%i", world->name, i );
		out->valid = Mod_CheckCubemap( va( "cube#%i", i ) ); // need for rebuild?
		if( !out->valid ) world->rebuilding_cubemaps = CMREBUILD_INACTIVE_NEEDSREBUILD;
		VectorCopy( in->origin, out->origin );
		ClearBounds( out->mins, out->maxs );
		out->size = in->size;

		if( out->size <= 0 )
			out->size = DEFAULT_CUBEMAP_SIZE;
		out->size = NearestPOW( out->size, false );
		out->size = bound( 1, out->size, 512 );
	}

	// do not autorebuild
	if( world->rebuilding_cubemaps == CMREBUILD_INACTIVE_NEEDSREBUILD )
	{
		ConPrintf( "^3Warning:^7 Map has %i cubemaps which require rebuilding. Run 'buildcubemaps' to build them.\n", world->num_cubemaps );
		world->build_default_cubemap = false;
		world->cubemaps_ready = false;
	}
	else if( world->loading_cubemaps )
	{
		world->cubemaps_ready = true;
	}
}

/*
=================
CL_FindNearestCubeMap

find the nearest cubemap for a given point
=================
*/
void CL_FindNearestCubeMap( const Vector &pos, mcubemap_t **result )
{
	if( !result ) return;

	float maxDist = 99999.0f;
	*result = NULL;

	for( int i = 0; i < world->num_cubemaps; i++ )
	{
		mcubemap_t *check = &world->cubemaps[i];
		float dist = VectorDistance( check->origin, pos );

		if( dist < maxDist )
		{
			*result = check;
			maxDist = dist;
		}
	}

	if( !*result )
	{
		// this may happen if map
		// doesn't have any cubemaps
		*result = &world->defaultCubemap;
	}
}

void CL_FindNearestCubeMapBox( const Vector &pos, mcubemap_t **result )
{
	if( !result ) return;

	float maxBoxsize = 99999.0f;
	*result = NULL;

	for( int i = 0; i < world->num_cubemaps; i++ )
	{
		mcubemap_t *check = &world->cubemaps[i];
		float dist = VectorDistance( check->origin, pos );
		float boxsize = (check->mins - check->maxs).Length();

		if( PointInBounds( pos, check->mins, check->maxs ) && (boxsize < maxBoxsize) )
		{
			*result = check;
			maxBoxsize = boxsize;
		}
	}

	// if the cubemap wasn't found, black cubemap will be used (no reflection effect)
}

/*
=================
CL_FindNearestCubeMapForSurface

find the nearest cubemap on front of plane
=================
*/
void CL_FindNearestCubeMapForSurface(const Vector& pos, const msurface_t* surf, mcubemap_t** result)
{
	if (!result) return;

	float maxDist = 99999.0f;
	mplane_t plane;
	*result = NULL;

	plane = *surf->plane;

	if (FBitSet(surf->flags, SURF_PLANEBACK))
	{
		plane.normal = -plane.normal;
		plane.dist = -plane.dist;
	}

	for (int i = 0; i < world->num_cubemaps; i++)
	{
		mcubemap_t* check = &world->cubemaps[i];
		float dist = VectorDistance(check->origin, pos);

		if (dist < maxDist && PlaneDiff(check->origin, &plane) >= 0.0f)
		{
			*result = check;
			maxDist = dist;
		}
	}

	if (*result) return;

	// fallback to default method
	CL_FindNearestCubeMap(pos, result);
}

void CL_FindNearestCubeMapBoxForSurface( const Vector &pos, const msurface_t *surf, mcubemap_t **result )
{
	if( !result ) return;

	float maxBoxsize = 99999.0f;
	mplane_t plane;
	*result = NULL;

	plane = *surf->plane;

	if( FBitSet( surf->flags, SURF_PLANEBACK ) )
	{
		plane.normal = -plane.normal;
		plane.dist = -plane.dist;
	}

	for( int i = 0; i < world->num_cubemaps; i++ )
	{
		mcubemap_t *check = &world->cubemaps[i];
		float dist = VectorDistance( check->origin, pos );
		float boxsize = (check->mins - check->maxs).Length();

		if( PointInBounds( surf->info->origin, check->mins, check->maxs) && (boxsize < maxBoxsize) )
		{
			*result = check;
			maxBoxsize = boxsize;
		}
	}

	// if the cubemap wasn't found, black cubemap will be used (no reflection effect)
}

/*
=================
CL_FindTwoNearestCubeMap

find the two nearest cubemaps for a given point
=================
*/
void CL_FindTwoNearestCubeMap(const Vector& pos, mcubemap_t** result1, mcubemap_t** result2)
{
	if (!result1 || !result2)
		return;

	float maxDist1 = 99999.0f;
	float maxDist2 = 99999.0f;
	*result1 = *result2 = NULL;

	for (int i = 0; i < world->num_cubemaps; i++)
	{
		mcubemap_t* check = &world->cubemaps[i];
		float dist = VectorDistance(check->origin, pos);

		if (dist < maxDist1)
		{
			*result1 = check;
			maxDist1 = dist;
		}
		else if (dist < maxDist2 && dist > maxDist1)
		{
			*result2 = check;
			maxDist2 = dist;
		}
	}

	if (!*result1)
	{
		// this may happen if map
		// doesn't have any cubemaps
		*result1 = &world->defaultCubemap;
	}

	if (!*result2)
	{
		// this may happen if map
		// doesn't have any cubemaps
		*result2 = *result1;
	}
}

/*
=================
CL_FindTwoNearestCubeMapForSurface

find the two nearest cubemaps on front of plane
=================
*/
void CL_FindTwoNearestCubeMapForSurface(const Vector& pos, const msurface_t* surf, mcubemap_t** result1, mcubemap_t** result2)
{
	if (!result1 || !result2) return;

	float maxDist1 = 99999.0f;
	float maxDist2 = 99999.0f;
	mplane_t plane;
	*result1 = NULL;
	*result2 = NULL;

	plane = *surf->plane;

	if (FBitSet(surf->flags, SURF_PLANEBACK))
	{
		plane.normal = -plane.normal;
		plane.dist = -plane.dist;
	}

	for (int i = 0; i < world->num_cubemaps; i++)
	{
		mcubemap_t* check = &world->cubemaps[i];
		float dist = VectorDistance(check->origin, pos);

		if (dist < maxDist1 && PlaneDiff(check->origin, &plane) >= 0.0f)
		{
			*result1 = check;
			maxDist1 = dist;
		}
		else if (dist < maxDist2 && dist > maxDist1)
		{
			*result2 = check;
			maxDist2 = dist;
		}
	}

	if (*result1)
	{
		if (!*result2)
			*result2 = *result1;
		return;
	}

	// fallback to default method
	CL_FindTwoNearestCubeMap(pos, result1, result2);
}

/*
=================
CL_BuildCubemaps_f

force to rebuilds all the cubemaps
in the scene
=================
*/
void CL_BuildCubemaps_f( void )
{
	mcubemap_t *m = &world->defaultCubemap;

	if( m->texture != tr.whiteCubeTexture )
		FREE_TEXTURE( m->texture );

	m->valid = m->texture = false;

	for( int i = 0; i < world->num_cubemaps; i++ )
	{
		mcubemap_t *m = &world->cubemaps[i];
		if( m->texture != tr.whiteCubeTexture )
			FREE_TEXTURE( m->texture );
		m->valid = m->texture = false;
	}

	world->cubemaps_ready = false;

	if( tr.lowmemory )
		return;

	if( FBitSet( world->features, WORLD_HAS_SKYBOX ) )
		world->build_default_cubemap = true;
	else
		world->build_default_cubemap = false;

	world->rebuilding_cubemaps = CMREBUILD_CHECKING;
	world->loading_cubemaps = true;
}

void R_InitCubemaps()
{
	gEngfuncs.pfnAddCommand("buildcubemaps", CL_BuildCubemaps_f);
}

/*
==================
GL_LoadAndRebuildCubemaps

rebuild cubemaps that older than bspfile
loading actual cubemaps into videomemory
==================
*/
void GL_LoadAndRebuildCubemaps( int refParams )
{
	if( !world->loading_cubemaps && world->rebuilding_cubemaps < CMREBUILD_CHECKING )
		return; // job is done

	// we are in cubemap-rendering mode
	if( FBitSet( refParams, RP_ENVVIEW ) )
		return;

	if( world->rebuilding_cubemaps > CMREBUILD_INACTIVE_NEEDSREBUILD )
	{
		if( world->build_default_cubemap )
		{
			mcubemap_t *cm = &world->defaultCubemap;

			if( world->rebuilding_cubemaps == CMREBUILD_WAITING )
			{
				cm->valid = Mod_CheckCubemap( "default" ); // need for rebuild?
				world->rebuilding_cubemaps = CMREBUILD_CHECKING;

				if( !cm->valid )
					ALERT( at_error, "GL_RebuildCubemaps: can't build default cubemap\n" );
				world->build_default_cubemap = false; // done
			}

			if( world->build_default_cubemap )
			{
				Mod_DeleteCubemap( "default" );

				// NOTE: engine function EnvShot not makes shots immediately
				// but create a queue. So we will wait for a next frame
				ENV_SHOT( cm->origin, va( "%s.tga", cm->name ), false, cm->size );
				world->rebuilding_cubemaps = CMREBUILD_WAITING;
				return;
			}
		}

		for( ; world->cubemap_build_number < world->num_cubemaps; world->cubemap_build_number++ )
		{
			mcubemap_t *cm = &world->cubemaps[world->cubemap_build_number];

			if( world->rebuilding_cubemaps == CMREBUILD_WAITING )
			{
				cm->valid = Mod_CheckCubemap( va( "cube#%i", world->cubemap_build_number ) ); // need for rebuild?
				world->rebuilding_cubemaps = CMREBUILD_CHECKING;

				if( !cm->valid )
				{
					ALERT( at_error, "GL_RebuildCubemaps: can't build cube#%i\n", world->cubemap_build_number );
					continue; // to avoid infinity cycle
				}
			}

			if( cm->valid ) continue; // it's valid cubemap

			Mod_DeleteCubemap( va( "cube#%i", world->cubemap_build_number ) );

			// NOTE: engine function EnvShot not makes shots immediately
			// but create a queue. So we will wait for a next frame
			ENV_SHOT( cm->origin, va( "%s.tga", cm->name ), false, cm->size );
			world->rebuilding_cubemaps = CMREBUILD_WAITING;
			return;
		}

		// we reached the end of list
		// next frame will be restored gamma
		SetBits( vid_brightness->flags, FCVAR_CHANGED );
		SetBits( vid_gamma->flags, FCVAR_CHANGED );
		world->rebuilding_cubemaps = CMREBUILD_INACTIVE;
		world->cubemap_build_number = 0;
		tr.params_changed = true;
		tr.glsl_valid_sequence++;
		tr.fClearScreen = false;
		world->cubemaps_ready = true;
	}

	// now all the cubemaps are recreated, so we can start to upload them
	if( world->loading_cubemaps )
	{
		Mod_LoadCubemap( &world->defaultCubemap );

		int i, j;
		for( i = 0; i < world->num_cubemaps; i++ )
		{
			mcubemap_t *cm = &world->cubemaps[i];
			Vector vecStart, vecEnd;
			pmtrace_t pmtrace;

			Mod_LoadCubemap( cm );
		}

		// bind cubemaps onto world surfaces
		// so we don't need to search them again
		for( i = 0; i < worldmodel->numsurfaces; i++ )
		{
			msurface_t *surf = &worldmodel->surfaces[i];
			mextrasurf_t *es = surf->info;

			CL_FindNearestCubeMapBoxForSurface( es->origin, surf, &es->cubemap );
		}

		world->loading_cubemaps = false;
	}
}