#include "const.h"
#include "mathlib.h"
#include "texfetch.h"

uniform sampler2D	u_ColorMap;
uniform vec2		u_ScreenSizeInv; // not inverted

varying vec2	var_TexCoord;

/***** RCAS *****/
#define FSR_RCAS_LIMIT (0.25-(1.0/16.0))
#define FSR_RCAS_DENOISE

vec4 FsrRcasLoadF( vec2 p )
{
	return texture2D( u_ColorMap, p / u_ScreenSizeInv );
}

void FsrRcasCon(
	out float con,
	// The scale is {0.0 := maximum, to N>0, where N is the number of stops (halving) of the reduction of sharpness}.
	float sharpness
)
{
	// Transform from stops to linear value.
	con = exp2( -sharpness );
}

vec3 FsrRcasF(
	vec2 ip, // Integer pixel position in output.
	float con
)
{
	// Constant generated by RcasSetup().
	// Algorithm uses minimal 3x3 pixel neighborhood.
	//    b 
	//  d e f
	//    h
	vec2 sp = vec2( ip );
	vec3 b = FsrRcasLoadF( sp + vec2( 0, -1 ) ).rgb;
	vec3 d = FsrRcasLoadF( sp + vec2( -1, 0 ) ).rgb;
	vec3 e = FsrRcasLoadF( sp ).rgb;
	vec3 f = FsrRcasLoadF( sp + vec2( 1, 0 ) ).rgb;
	vec3 h = FsrRcasLoadF( sp + vec2( 0, 1 ) ).rgb;
	// Luma times 2.
	float bL = b.g + .5 * (b.b + b.r);
	float dL = d.g + .5 * (d.b + d.r);
	float eL = e.g + .5 * (e.b + e.r);
	float fL = f.g + .5 * (f.b + f.r);
	float hL = h.g + .5 * (h.b + h.r);
#ifdef FSR_RCAS_DENOISE
	// Noise detection.
	float nz = .25 * (bL + dL + fL + hL) - eL;
	float maxL = max( max( bL, dL ), max( eL, max( fL, hL ) ) );
	float minL = min( min( bL, dL ), min( eL, min( fL, hL ) ) );
	float denom = maxL - minL;
	denom = max(denom, 1e-6); // Small epsilon to avoid zero
	nz = clamp( abs( nz ) / denom, 0., 1. );
	nz = 1. - .5 * nz;
#endif
	// Min and max of ring.
	vec3 mn4 = min( b, min( f, h ) );
	vec3 mx4 = max( b, max( f, h ) );
	// Immediate constants for peak range.
	vec2 peakC = vec2( 1., -4. );
	// Limiters, these need to be high precision RCPs.
	vec3 hitMin = mn4 / (4. * mx4);
	vec3 hitMax = (peakC.x - mx4) / (4. * mn4 + peakC.y);
	vec3 lobeRGB = max( -hitMin, hitMax );
	float lobe = max(
		-FSR_RCAS_LIMIT,
		min( max( lobeRGB.r, max( lobeRGB.g, lobeRGB.b ) ), 0. )
	) * con;
	// Apply noise removal.
#ifdef FSR_RCAS_DENOISE
	lobe *= nz;
#endif
	// Resolve, which needs the medium precision rcp approximation to avoid visible tonality changes.
	return (lobe * (b + d + h + f) + e) / (4. * lobe + 1.);
}

void main( void )
{
	// Normalized pixel coordinates (from 0 to 1)
	vec2 uv = var_TexCoord;

	// Set up constants
	float con;
	float sharpness = 0.25;

	FsrRcasCon( con, sharpness );

	// Perform RCAS pass
	vec3 col = FsrRcasF( gl_FragCoord.xy, con );

	gl_FragColor = vec4( col, 1 );
}